// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dedbpbswvqiimphdnjuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZGJwYnN3dnFpaW1waGRuanV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NzAzNjYsImV4cCI6MjA2MzM0NjM2Nn0.1ZUUVS3akiT3nGzsiv8-_36bTkNbDDcMQ7q3FtzGfHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);